### ISSUE TITLE
Programmatically placed foods should not be removed

### ISSUE THREAD

**Issue by Glanzer-modder** [Coyote21/Food-Remover-Plus#1]
Hi Coyote21, thanks for the new version of this great patcher. I've been using a modified version of your original FoodRemover in which I skipped all owned food. I see you have that built into the new version! You should consider skipping over food that is enabled or disabled programmatically so that any quests or scripts will proceed correctly. Here is the code I was using in your main foreach loop to do that:

if (placedObjectGetter.Record.EnableParent != null) continue;

**Comment by Coyote21** [comment]
Thanks again Glanzer, I think I'm gonna have to start crediting this as a collaborative effort in future. Or at least I'll be including you in any "Thanks to" I write.

I'm still only halfway through working on this, I was called back to RL rather abruptly earlier this year before I had time to finish it, but I will certainly incorporate your suggestion when I do start with it again. 

Hopefully, I will be able to re-engage with this before the end of March or very early April at the latest.

That being said, I'm surprised you even found this. I know the repository is Public but I did not think this was showing in Synthesis yet? As mentioned I don't really have time to investigate right now, so can you confirm if you found this through Synthesis? or by some other means?

**Comment by Glanzer-modder** [comment]
Yeah it just appeared in the public list inside Synthesis. It should do that automatically based on certain criteria that get scanned. I talked with the guy who programmed the scanner and he helped to get my own synthesis patcher in the public list when it was having trouble. He said it should happen automatically.

**Comment by Coyote21** [comment]
Yah, Noggog is great like that. I also had issues with getting this listed and they told me what to do to fix it.
I never did the fixes tho (b/c I was called away), so I assumed it was still not publicly listed, and I was in no hurry.

Noggog, must have seen that I had not made the fixes yet, and decided to help me out. Oh well, I've slapped a warning in the readme.md and that will have to do for now.

**Comment by Glanzer-modder** [comment]
Yeah he basically had to give me the code to make part of my synthesis patcher work. Great guy. So should I continue using your old version until this one is ready?

**Comment by Coyote21** [comment]
Your choice.

It seems to me that you have the knowledge and skills to decide for yourself if the new version may cause you more problems than it's worth. I won't mind (don't care) whether you use my new code, use my old code while you wait for me to work on it some more, or even if you wholesale copy it, modify it and use it yourself or even release your own version.

I made it for myself, and to learn how to do it. How anyone else uses the code is up to them. Ofc if you do release a version yourself and somehow make a fortune with it, then I'll want a cut, but until then, go your hardest.

**Comment by Glanzer-modder** [comment]
The modified version I'm using now will work fine, I'll wait till you have time to get the new version finished before using it. But I may look through your code to see how you're doing things when I need to do another synthesis patcher. I probably dabble in too many things to learn anything well. LOL

**Comment by Coyote21** [comment]
If you're still around and playing Skyrim. I finally got back to Skyrim myself again (again) and fixed up the code including your suggestions. Feel free to give it a go, it should be available using the 'add Github Repository' button and using food-remover-plus in the filter.

**Comment by Glanzer-modder** [comment]
Hey thanks for letting me know! I'll check it out.
